### ISSUE TITLE
Publisher Reconnect

### ISSUE THREAD

**Issue by chriskolenko** [jdextraze/go-gesclient#24]
I have an application that runs forever and publishes messages from a websocket to eventstore.

When the connect fails, the program stops working.

This is because the connection is closed. Does anyone have an example on how this should work? I'm happy to send a PR with an example if someone could explain best way to do it.

**Comment by jdextraze** [comment]
Hi @chriskolenko,

I have some questions:
- Do you know why your connection is failing?
- What connection settings are you using?

Of course seeing your code would help understand the problem.

**Comment by chriskolenko** [comment]
```
	settingsBuilder := client.CreateConnectionSettings().
		KeepReconnecting()
```

That fixed my issue.

**Comment by jdextraze** [comment]
Ok thanks for the update. Closing this issue.
