### ISSUE TITLE
ConnectPersistentSubscription: Message is wrong

### ISSUE THREAD

**Issue by chriskolenko** [jdextraze/go-gesclient#28]
I'm seeing $> as my Event Type when getting a message from a Subscription. 

Just debugging now, but there is nothing strange in my code: 

Event Store 4.1.1.0
ConnectionString: tcp://admin:changeit@localhost:1113

```
	task, err := conn.ConnectToPersistentSubscriptionAsync(stream, groupName,
		eventAppeared, subscriptionDropped,
		nil, 10, true)

	if err != nil {
		return nil, err
	}

	if err := task.Error(); err != nil {
		return nil, err
	}

	return task.Result().(client.PersistentSubscription), nil
```

```
	eventAppeared := func(_ client.PersistentSubscription, e *client.ResolvedEvent) error {
		pretty.Print(e.String()) <- Wrong there
		pretty.Print(e) <- Wrong here

		evt := e.Event()
		p.self.Tell(evt)
		return nil
	}
```

**Comment by chriskolenko** [comment]
Ok, found a new clue

It works fine with standard EventStreams.. but not with Projected Ones. 

In my case:
discord_guild-360914338606743553 <- works
$ce-discord_guild <- Doesn't work

**Comment by chriskolenko** [comment]
![screen shot 2018-09-02 at 1 55 23 pm](https://user-images.githubusercontent.com/1318186/44952040-1b4c4980-aeb8-11e8-8eba-1611c3062eba.png)

I get the event if the Resolve Link is checked.

**Comment by jdextraze** [comment]
Hi @chriskolenko, sorry for the delay.

Projection streams use **Link** which are represented by **$>** in the event type. So when listening to a projection stream, always use the **Resolve Link To** option.
